Adding Automatic Initailization for Kafka, Kibana, Elastic Search and MinIO

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,4 +1,3 @@
-version: '3.8'
 
 services:
 
@@ -9,12 +8,19 @@ services:
       ZOOKEEPER_CLIENT_PORT: 2181
     networks:
       - kafka-net
-    # volumes:
-    #   - ./zookeeper_data:/var/lib/zookeeper
+    volumes:
+      - zookeeper_data:/var/lib/zookeeper
 
   kafka:
     image: confluentinc/cp-kafka:7.6.0
     container_name: kafka
+
+    healthcheck:
+      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
+      interval: 10s
+      timeout: 10s
+      retries: 10    
+
     depends_on:
       - zookeeper
     ports:
@@ -31,6 +37,30 @@ services:
     #   - ./kafka_data:/var/lib/kafka/data
     networks:
       - kafka-net
+    volumes:
+      - kafka_data:/var/lib/kafka/data      
+  kafka-init:
+    image: confluentinc/cp-kafka:7.6.0
+    depends_on:
+      kafka:
+        condition: service_healthy
+    entrypoint: >
+      sh -c "
+        echo 'Waiting for Kafka...'
+
+        until kafka-topics --bootstrap-server kafka:9092 --list >/dev/null 2>&1; do
+          echo 'Kafka not ready yet...'
+          sleep 5
+        done
+
+        echo 'Creating topic iot-data...'
+
+        kafka-topics --create --if-not-exists --topic iot-data --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
+
+        echo 'Kafka topic created successfully.'
+      "
+    networks:
+      - kafka-net    
   kafka-ui:
     image: provectuslabs/kafka-ui:latest
     container_name: kafka-ui
@@ -77,14 +107,15 @@ services:
     image: postgres:15
     container_name: postgres
     environment:
-      POSTGRES_USER: user
-      POSTGRES_PASSWORD: password
-      POSTGRES_DB: db
+      POSTGRES_USER: ${POSTGRES_USER}
+      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
+      POSTGRES_DB: ${POSTGRES_DB}
     ports:
       - "5432:5432"
     networks:
       - kafka-net
     volumes:
+      - postgres_data:/var/lib/postgresql/data
       - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
       
   jupyter:
@@ -97,27 +128,88 @@ services:
       - kafka-net
     environment:
       - SPARK_MASTER=spark://spark-master:7077
-      - JUPYTER_TOKEN=123
+      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
     volumes:
       - .:/home/jovyan/work
       - ./jars:/home/jovyan/jars
   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
+    healthcheck:
+      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
+      interval: 10s
+      timeout: 10s
+      retries: 10    
     environment:
       - discovery.type=single-node
       - xpack.security.enabled=false
     ports:
       - "9200:9200"
     networks:
-      - kafka-net      
+      - kafka-net  
+    volumes:
+      - elasticsearch_data:/usr/share/elasticsearch/data          
+  elasticsearch-init:
+    image: curlimages/curl
+    depends_on:
+      elasticsearch:
+        condition: service_healthy
+    entrypoint: >
+      sh -c "
+        echo 'Waiting for Elasticsearch...'
+
+        until curl -s http://elasticsearch:9200 >/dev/null; do
+          echo 'Elasticsearch not ready yet...'
+          sleep 5
+        done
+
+        echo 'Applying template...'
+
+        curl -X PUT http://elasticsearch:9200/_index_template/iot_template -H 'Content-Type: application/json' -d @/templates/iot-template.json
+
+        echo 'Template applied successfully.'
+      "
+    volumes:
+      - ./elasticsearch/templates:/templates
+    networks:
+      - kafka-net    
   kibana:
     image: docker.elastic.co/kibana/kibana:8.13.0
     ports:
       - "5601:5601"
     depends_on:
-      - elasticsearch
+      elasticsearch:
+        condition: service_healthy
     networks:
-      - kafka-net      
+      - kafka-net     
+  kibana-init:
+    image: curlimages/curl
+    depends_on:
+      kibana:
+        condition: service_started
+
+    entrypoint: >
+      sh -c "
+        echo 'Waiting for Kibana...'
+
+        until curl -s http://kibana:5601/api/status | grep -q 'available'; do
+          echo 'Kibana not ready yet...'
+          sleep 5
+        done
+
+        echo 'Importing Kibana objects...'
+
+        until curl -f -X POST 'http://kibana:5601/api/saved_objects/_import?overwrite=true' -H 'kbn-xsrf: true' --form 'file=@/exports/export.ndjson'; do
+
+          echo 'Import failed, retrying in 5 seconds...'
+          sleep 5
+        done
+
+        echo 'Kibana import completed successfully.'
+      "
+    volumes:
+      - ./kibana/exports:/exports
+    networks:
+      - kafka-net   
   minio:
     image: minio/minio
     container_name: minio
@@ -125,16 +217,35 @@ services:
       - "9000:9000"
       - "9001:9001"
     environment:
-      MINIO_ROOT_USER: admin
-      MINIO_ROOT_PASSWORD: password123
+      MINIO_ROOT_USER: ${MINIO_USER}
+      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
     command: server /data --console-address ":9001"
     volumes:
       - ./minio_data:/data
     networks:
       - kafka-net
+  minio-init:
+    image: minio/mc
+    depends_on:
+      - minio
+    entrypoint: >
+      /bin/sh -c "
+        until mc alias set myminio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}; do
+          echo 'MinIO not ready yet...'
+          sleep 5
+        done;
+
+        mc mb myminio/iot-data || true;
+
+        exit 0;
+      "
+    networks:
+      - kafka-net
 volumes:
   kafka_data:
-
+  zookeeper_data:
+  postgres_data:
+  elasticsearch_data:
 networks:
   kafka-net:
     driver: bridge
